#
# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
#
config_version: 3
default_language: en_US
# Enable this option if you're using plugin on a Velocity network
velocity_support: false
show_dependency_suggestions: true

bstats: true
# Leave sounds blank to disable them
# Ex: command: ""
sounds:
    command: "ENTITY_EXPERIENCE_ORB_PICKUP"
    vanish: "ENTITY_EXPERIENCE_ORB_PICKUP"
    unvanish: "ENTITY_EXPERIENCE_ORB_PICKUP"
vanish:
    # Show players actionbar when they are vanished
    actionbar: true
    # Remember vanish data after switch servers?
    # Note: Need Velocity as proxy server and `velocity_support` enabled
    remember: true
    # Should we change player type to spectator in tablist for players who have permission to see vanished players?
    # Note: Requires ProtocolLib
    see_as_spectator: true
    # Should vanished players be protected from all damage sources?
    invincible: true
    # Prevent vanished players from pickup items
    prevent_pickup: true
    # Note: Not working when some ProCosmetics cosmetics are enabled!
    silent_open_container: true